### ISSUE TITLE
Redirect to payment page not working in Magento 2.4.6-p4

### ISSUE THREAD

**Issue by abecker87** [mollie/magento2-hyva-checkout#17]
**Describe the bug**
We just tried to update our project to Magento 2.4.6-p4 and detected a problem with the mollie integration.
We’re not sure if it is a general problem or related to our setup.

After clicking the place order button, the page ‘Order process completed successfully. You are being redirected, please wait...’ appears and we are not redirected to the mollie payment page. Instead, we are redirected to checkout/onepage/success/.

In Magento 2.4.6-p3 everything worked as expected.

**Used versions**
magento/product-community-edition 2.4.6-p4
mollie/magento2 2.35.0
mollie/magento2-hyva-checkout 1.3.0
mollie/magento2-hyva-compatibility 2.1.0
hyva-themes/magento2-hyva-checkout 1.1.13
hyva-themes/magento2-default-theme 1.3.4
hyva-themes/magento2-theme-module 1.3.4

We have no other payment methods installed. 
There are no console errors and no no errors in var/log files.

**Comment by Tjitse-E** [comment]
@Frank-Magmodules  I can confirm this issue. It's introduced by `hyva-themes/magento2-hyva-checkout` 1.1.13. We did a rollback to 1.1.12 and that fixes the issue. I don't think it has anything to do with magento 2.4.6-p4.

This does mean that the Mollie Hyvä checkout extension is currently is not Hyvä  checkout 1.1.13 compatible.

**Comment by Frank-Magmodules** [comment]
Thanks @Tjitse-E , @abecker87 , We are on it!

**Comment by sprankhub** [comment]
https://docs.hyva.io/checkout/hyva-checkout/upgrading/upgrading-to-1.1.13.html#backward-incompatible-changes

**Comment by web4exposure-org** [comment]
Just to be sure, is this compatible to 1.1.14 too?

**Comment by Frank-Magmodules** [comment]
Hi There @web4exposure-org and all,
As you might have noticed, we released version [1.3.1](https://github.com/mollie/magento2-hyva-checkout/releases/tag/1.3.1) today, which addresses this issue. The issue is caused by a change on the side of the Hyvä Checkout. Hyvä rolled back the change and released version 1.1.14. We checked, and our module works as expected with that version too.

Thank you once more, @Tjitse-E! 
We're marking this issue as resolved for now, but please feel free to reopen it whenever you deem it necessary.
