### ISSUE TITLE
Apple Button now showing

### ISSUE THREAD

**Issue by mokadev** [mollie/magento2-hyva-checkout#27]
Hi 

I am encountering an issue with the Apple Pay button that does not appear when I select this payment method. It is indeed in the HTML body but the 'hidden' class does not remove when ticking the radio button.

The certificate is accessible and i'm on a live site. 

Do you have any idea what the possible cause could be?

**Comment by Frank-Magmodules** [comment]
Hi there @mokadev, since we’re unable to reproduce the issue, could you [share](https://www.magmodules.eu/help#:~:text=products%20and%20services.-,Support%20by%20e%2Dmail,-contact%40magmodules.eu) more details with us directly? 
We’d like to take a closer look at your environment to better understand what’s happening and figure out how we can assist in resolving the issue. Thanks so much!

**Comment by mokadev** [comment]
Hi @Frank-Magmodules 

I will send you a mail with more details but can you explain how this "hidden" class is removed from this line: [https://github.com/mollie/magento2-hyva-checkout/blob/f0e3a4e361b3a497765e8c5eaec900f63c4aab55/src/Mollie_HyvaCheckout/view/frontend/templates/component/payment/method/applepay.phtml#L11](url) ? it will help me understand what I'm missing. 

Thanks

**Comment by mokadev** [comment]
Arff my bad . I understood my error. It's OK now.

Thanks

**Comment by Frank-Magmodules** [comment]
I wish all issues would resolve themselves this easily ;-) 
Thanks, @mokadev! Glad you got it sorted!
